drop table if exists admins CASCADE;
drop table if exists calendars CASCADE;
drop table if exists companies CASCADE;
drop table if exists company_employees CASCADE;
drop table if exists company_leaders CASCADE;
drop table if exists company_types CASCADE;
drop table if exists customers CASCADE;
drop table if exists emails CASCADE;
drop table if exists events CASCADE;
drop table if exists files CASCADE;
drop table if exists interpreters CASCADE;
drop table if exists locations CASCADE;
drop table if exists login_attempts CASCADE;
drop table if exists price_patterns CASCADE;
drop table if exists price_pattern_price_mapping CASCADE;
drop table if exists roles CASCADE;
drop table if exists switching_call_center_employees CASCADE;
drop table if exists switching_call_center_leaders CASCADE;
drop table if exists switching_centers CASCADE;
drop table if exists timesheets CASCADE;
drop table if exists translators CASCADE;
drop table if exists user_news CASCADE;
drop table if exists users CASCADE;
drop sequence if exists event_seq;
drop sequence if exists hibernate_sequence;
drop sequence if exists location_seq;
drop sequence if exists price_pattern_seq;
